### ISSUE TITLE
Cannot create symlink

### ISSUE THREAD

**Issue by mjnewsum** [compas-dev/compas#1125]
**Describe the bug**
Cannot create symlink when installing compas to rhino 7.

**To Reproduce**
1. Context - Rhino 7, Windows 10, Python 3.11.0., miniconda conda 23.1.0, following Getting Started instructions
2. Sample script - I am using the commands from the Installation and Getting Started - Rhino Instructions.
3. Errors - I am trying to install compas for rhino for the first time on my work laptop. When I run the command `python -m compas_rhino.install` I get the following errors:

`(research) C:\dev\compas>python -m compas_rhino.install

Installing COMPAS packages to Rhino 7.0 scripts folder:
C:\Users\mnewsum\AppData\Roaming\McNeel\Rhinoceros\7.0\scripts       

   compas               ERROR: Cannot create symlink, try to run as administrator.
   compas_ghpython      ERROR: Cannot create symlink, try to run as administrator.
   compas_rhino         ERROR: Cannot create symlink, try to run as administrator.
   compas_bootstrapper  WARNING: One or more packages failed, will not install bootstrapper, try uninstalling first

Install completed.`

I did get a popup asking me to input admin user name and password, and I filled in my admin data correctly. I am not sure what else I can do... 

I tried opening the command prompt as administrator, and that only made things worse. When running the `python -m compas_rhino.install` command, rhino could not be found because rhino is installed on my user account not the administrator user.

**Expected behavior**
I expected compas to install python libraries for rhino.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python 3.11.0
 - Miniconda conda 23.1.0
 - This is a work laptop and I have admin login

**Additional context**
I did have some issues installing conda originally. I was getting SSL Certificate errors because my computer has ZScaler installed. I added appropriate ZScaler certificate.crt, and the issue went away. I don't think this is causing the current problem, but I figured it was worth noting. 

I did try installing compas with pip because I was having so many issues with conda. When I did this, the installation seemed to go fine, but when I opened rhino's python editor after trying to install compas, rhino will crash if I run a script that includes "import compas".

I am not sure what all I need to do to remove the installation files or try to fix the issues.

**Comment by mjnewsum** [comment]
Ok, I found the linked files in my scripts folder and removed them. This fixed the symlink error. It was not an issue with permissions; it wasn't working because the links already exist. 

I removed the files and ran the `python -m compas_rhino.install` again and it looks like it worked fine.

`(research) C:\Users\mnewsum.RELATIVITYCO>python -m compas_rhino.install

Installing COMPAS packages to Rhino 7.0 scripts folder:
C:\Users\mnewsum\AppData\Roaming\McNeel\Rhinoceros\7.0\scripts

   compas               OK
   compas_ghpython      OK
   compas_rhino         OK
   compas_bootstrapper  OK

Running post-installation steps...

   compas_ghpython      OK: Installed 5 GH User Objects

Install completed.`

When I open rhino and run this in the python IDE `import compas` rhino freezes for a minute then crashes without any popups. 

If I open rhino and grasshopper and try to use one of the compas user objects, rhino freezes and crashes in the same way.

**Comment by gonzalocasas** [comment]
mmm... the issue with the existing symlinks could (probably) also be solved with `python -m compas_rhino.uninstall` beforehand, but manual removal should also be perfectly fine. 

As for the freeze & crash of Rhino, that's unexpected. Does the crash log of Rhino contain any hints?

**Comment by gonzalocasas** [comment]
oh.. did the crash disappear?

**Comment by mjnewsum** [comment]
No, the crash didn't disappear. I was thinking I should close the original issue and file this as a separate issue. Sorry for the confusion. Rhino is still crashing if I use compas in python or grasshopper.

**Comment by mjnewsum** [comment]
When rhino crashes, I don't get any popup or anything, so I'm not sure where to look for rhino errors.
